### ISSUE TITLE
Issues 24-01-15

### ISSUE THREAD

**Issue by zxr19980213** [HuBoren99/SmartBert#1]
1. github仓库里给出的download_glue.py脚本似乎是旧版本的，对于STS和QQP数据集的下载链接是颠倒的(Line 31-32)，不知道该设置是否会对实验结果造成异常影响。
2. 在models/SmartBert.py文件中，Line 179-180处判断index=num_layers-1并再次计算logits的操作似乎与 Line 172重复。我能想到可能不一致的操作流是，模型始终没有early exit，但是在最后一层执行了skip。这段代码的目的是确保整个模型在没有early exit的情况下，使用最后一层的classifer得到输出的logits(即使hidden不是由最后一层的encoder得到)。或者这段代码有什么我没有理解的巧妙用意吗？

**Comment by HuBoren99** [comment]
感谢您的关注～关于您的问题，我将一一回复：

1. 抱歉，这个代码是有问题，我已经更改了

2. 您的理解是对的，如果运行了Line179-180表明模型没有早退，因此我们使用最后一层的classifier计算logits，当然也可以使用之前的logits作为结果。







-----原始邮件-----
发件人:"Xiangrong Zhu" ***@***.***>
发送时间:2024-01-15 11:13:37 (星期一)
收件人: HuBoren99/SmartBert ***@***.***>
抄送: Subscribed ***@***.***>
主题: [HuBoren99/SmartBert] Issues 24-01-15 (Issue #1)






github仓库里给出的download_glue.py脚本似乎是旧版本的，对于STS和QQP数据集的下载链接是颠倒的(Line 31-32)，不知道该设置是否会对实验结果造成异常影响。
在models/SmartBert.py文件中，Line 179-180处判断index=num_layers-1并再次计算logits的操作似乎与 Line 172重复。我能想到可能不一致的操作流是，模型始终没有early exit，但是在最后一层执行了skip。这段代码的目的是确保整个模型在没有early exit的情况下，使用最后一层的classifer得到输出的logits(即使hidden不是由最后一层的encoder得到)。或者这段代码有什么我没有理解的巧妙用意吗？
